version: "3.4"

services:

  redis:
    image: redis:5.0.4-stretch
    container_name: redis
    env_file:
      - .env
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    volumes:
      - redis:/data

  db:
    image: postgres:latest
    container_name: postgres
    env_file: 
      - database.conf
    ports:
      - ${DOCKER_SQL_PORT:-127.0.0.1:5432}:5432
    volumes:
      - db_volume:/var/lib/postgresql

  droznik-api:
    image: pociagi/droznik-api
    container_name: droznik-api
    build:
      context: ./pociagi/droznik
      dockerfile: .
    command: celery -A pociagi.droznik.droznik:celery worker -B -l info -E -Q droznik
    depends_on:
      - redis
    env_file:
      - .env
      - database.conf
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    ports:
      - 1100:1100
    volumes:
      - ${DOCKER_WEB_VOLUME:-./public:/app/public}

  pociag-client:
    image: pociagi/pociag-client
    container_name: pociag-client
    build:
      context: ./pociagi/pociag
      dockerfile: .
    command: celery -A pociag:celery worker -B -l info -E -Q pociag
    depends_on:
      - redis

  centrala-api:
    image: pociagi/centrala-api
    container_name: centrala-api
    build:
      context: ./pociagi/centrala
      dockerfile: .
    command: celery -A centrala:celery worker -B -l info -E -Q centrala
    depends_on:
      - redis
    ports:
      - "1200:1200"
    volumes:
      - centrala:/logs

volumes:
  redis: {}
  db_volume: {}
  centrala: {}